Feature/deletevideo
DiegoAvmor/RestfulStreamingAPI pull request #10
Opened 2021-01-11 07:06 UTC by MRico98

2021-01-11 21:27 UTC, DiegoAvmor requested changes
Hay funciones definidas que deberian ser expuestas dentro de una clase de utileria y no dentro del propio servicio

2021-01-11 21:27 UTC, DiegoAvmor commented on src/main/java/com/api/streaming/service/impl/VideoServiceImpl.java
> +    private void checkUserAuthorization(User actualUser,Video video){
No podemos, sacar esta funcion a una clase de utileria para que otras parte del sistema pueda usar? @MRico98

2021-01-11 21:27 UTC, DiegoAvmor commented on src/main/java/com/api/streaming/service/impl/VideoServiceImpl.java
> +    private User getActualSession(){
Similar a lo anterior, podríamos sacar esto y ponerlo como funcion de una clase de utileria

2021-01-11 21:33 UTC, MRico98 commented
Creo que tanto la funcion getActualSession mas que ir en un util deberian estar en el service de users, ¿que opinas? @DiegoAvmor 

Ya la funcion checkUserAuthorization la podriamos colocar en un authorizationUtil

2021-01-11 21:34 UTC, DiegoAvmor commented
> Creo que tanto la funcion getActualSession mas que ir en un util deberian estar en el service de users, ¿que opinas? @DiegoAvmor
> 
> Ya la funcion checkUserAuthorization la podriamos colocar en un authorizationUtil

No, queda mas dentro de una clase de utileria debido a que el recurso de usuarios es el recurso como tal en ello no tiene nada que ver la parte de autorizacion en el cual el security context entra

2021-01-11 23:12 UTC, MRico98 commented
Cambios rrealizados en el commit [https://github.com/DiegoAvmor/RestfulStreamingAPI/commit/fef3fa1fd0cdecd98dbebf4462387dc0dad5000c](url)

2021-01-11 23:16 UTC, MRico98 commented
Cambios realizados en el commit [https://github.com/DiegoAvmor/RestfulStreamingAPI/commit/fef3fa1fd0cdecd98dbebf4462387dc0dad5000c](url)

2021-01-11 23:17 UTC, MRico98 commented
cambios reaizados en el commit fef3fa1fd0cdecd98dbebf4462387dc0dad5000c

2021-01-12 07:31 UTC, MRico98 commented
Se cierra ya que se necesita hacer merge de esta rama con feature/editvideo

2021-01-12 07:31 UTC, closed without merging